name: album-splitter CI
on: [push, pull_request]
jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - uses: pre-commit/action@v3.0.0

    smoke-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - name: Install package
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install .
            - name: Run album-splitter
              run: |
                  printf "00:06 When I Was Young\n03:35 Dogs Eating Dogs\n07:05 Disaster\n10:48 Boxing Day\n14:48 Pretty Little Girl" > tracks.txt
                  python -m album-splitter -yt "https://www.youtube.com/watch?v=p_uqD4ng9hw"
